MODEL:
  input_shape :  [224, 224, 3]
  encodings_len: 256
  mode : 'triplet'
  distance_type : 'l1'
  backbone_name : 'efficientnet-b3'
  backbone_weights : 'noisy-student'
  freeze_backbone : False
  embeddings_normalization: True

DATALOADER:
  dataset_path : '/home/rauf/datasets/aaaa/deepfake/'
  csv_file : 
  image_id_column : 
  label_column : 
  validate : True
  val_ratio : 0.2
  
GENERATOR:
  negatives_selection_mode : 'hardest'
  k_classes: 2
  k_samples: 3
  margin: 0.5
  batch_size : 8
  n_batches : 7000
  augmentations : 'deepfake'

TRAIN:
  # optimizer parameters
  optimizer : 'radam'
  learning_rate : 0.000016
  decay_factor : 0.99
  step_size : 1

  # embeddings learning training parameters
  n_epochs : 1000
  
  # plot training history
  plot_history : True

# SOFTMAX_PRETRAINING:
#   # softmax pretraining parameters
#   optimizer : 'radam'
#   learning_rate : 0.0001
#   decay_factor : 0.99
#   step_size : 1

#   batch_size : 16
#   val_steps : 200
#   steps_per_epoch : 1000
#   n_epochs : 50

SAVE_PATHS:
  project_name : 'deepfake_efn_b3'
  work_dir : 'work_dirs/'

ENCODINGS:
  # encodings parameters
  save_encodings : True
  centers_only: False
  max_num_samples_of_each_class : 30
  knn_k : 1