input_shape :  [48, 48, 3]
encodings_len: 256
margin: 0.5
mode : 'triplet'
distance_type : 'l1'
backbone : 'resnet18'
backbone_weights : 'imagenet'
freeze_backbone : False
augmentation_type : 'default'
min_n_obj_per_class : 30 
select_max_n_obj_per_class : 30
max_n_obj_per_class : 10000
embeddings_normalization: True

# optimizer parameters
optimizer : 'radam'
learning_rate : 0.0001
decay_factor : 0.99
step_size : 1

# embeddings learning training parameters
n_epochs : 1000
n_steps_per_epoch : 200
val_batch_size : 8
val_steps : 500
negatives_selection_mode : 'semihard'
mining_n_classes: 5
mining_n_samples: 3

# softmax pretraining parameters
softmax_pretraining : True
softmax_batch_size : 8
softmax_val_steps : 200
softmax_steps_per_epoch : 800
softmax_epochs : 10

#paths
work_dir : 'work_dirs/paper_resnet18_with_softmax/'
dataset_path : '/home/rauf/datasets/road_signs/road_signs_separated/'
plot_history : True
model_save_name : 'best_model_paper_resnet18_with_softmax.h5'
encodings_save_name: 'encodings_paper_resnet18_with_softmax.pkl'

# encodings parameters
save_encodings : True
centers_only: False
max_num_samples_of_each_class : 30
knn_k : 1