input_shape :  [128, 128, 3]
encodings_len: 1024
mode : 'triplet'
distance_type : 'l1'
backbone : 'resnet50'
backbone_weights : 'imagenet'
optimizer : 'adam'
learning_rate : 0.0001
project_name : 'plates/'
freeze_backbone : True
augmentation_type : 'default'

#paths
dataset_path : '/home/rauf/plates_competition/dataset/to_train/'
tensorboard_log_path : 'tf_log/'
weights_save_path : 'weights/'
plots_path : 'plots/'
encodings_path : 'encodings/'
