input_shape :  [128, 128, 3]
encodings_len: 128
margin: 0.3
mode : 'triplet'
distance_type : 'l1'
backbone : 'resnext50'
backbone_weights : 'imagenet'
freeze_backbone : True
augmentation_type : 'plates2'
min_n_obj_per_class : 0 
select_max_n_obj_per_class : 30
max_n_obj_per_class : 10000
embeddings_normalization: True

# optimizer parameters
optimizer : 'radam'
learning_rate : 0.00001
decay_factor : 0.99999
step_size : 1

# embeddings learning training parameters
n_epochs : 1000
n_steps_per_epoch : 200
val_batch_size : 4
val_steps : 10
negatives_selection_mode : 'semihard'
mining_n_classes: 2
mining_n_samples: 3

# softmax pretraining parameters
softmax_pretraining : True
softmax_batch_size_train : 16
softmax_batch_size_val : 8
softmax_val_steps : 1
softmax_steps_per_epoch : 10
softmax_epochs : 100
softmax_is_binary: True

#paths
# paths
work_dir : 'work_dirs/plates_resnext50/'
dataset_path : '/home/rauf/datasets/plates/plates_splitted/'
plot_history : True
model_save_name : 'best_model_plates_resnext50.h5'
encodings_save_name: 'encodings_plates_resnext50.pkl'

# encodings parameters
save_encodings : True
centers_only: False
max_num_samples_of_each_class : 30
knn_k : 1