input_shape :  [128, 128, 3]
encodings_len: 128
margin: 0.4
mode : 'triplet'
distance_type : 'l2'
backbone : 'resnet18'
backbone_weights : 'imagenet'
freeze_backbone : True
augmentation_type : 'plates2'
min_n_obj_per_class : 0 
select_max_n_obj_per_class : 30
max_n_obj_per_class : 10000
embeddings_normalization: True
to_validate : False

# optimizer parameters
optimizer : 'radam'
learning_rate : 0.0001
decay_factor : 0.99999
step_size : 1

# embeddings learning training parameters
n_epochs : 1000
n_steps_per_epoch : 200
val_batch_size : 16
val_steps : 10
negatives_selection_mode : 'semihard'
mining_n_classes: 2
mining_n_samples: 7

# softmax pretraining parameters
softmax_pretraining : True
softmax_batch_size_train : 32
softmax_batch_size_val : 16
softmax_val_steps : 50
softmax_steps_per_epoch : 100
softmax_epochs : 100
softmax_is_binary: True

# paths
work_dir : 'work_dirs/plates/'
dataset_path : '/home/rauf/datasets/plates/plates_splitted/'
plot_history : True
model_save_name : 'best_model_plates_resnet18.h5'
encodings_save_name: 'encodings_plates_resnet18.pkl'

# encodings parameters
save_encodings : True
centers_only: False
max_num_samples_of_each_class : 30
knn_k : 1