input_shape :  [48, 48, 3]
encodings_len: 256
margin: 0.3
mode : 'triplet'
distance_type : 'l1'
backbone : 'resnet18'
backbone_weights : 'imagenet'
optimizer : 'radam'
learning_rate : 0.0001
project_name : 'road_signs/'
freeze_backbone : False
embeddings_normalization: False

#paths
dataset_path : '/home/rauf/datasets/road_signs/road_signs_mini/'
tensorboard_log_path : 'tf_log/'
weights_save_path : 'weights/'
plots_path : 'plots/'
encodings_path : 'encodings/'
model_save_name : 'best_model_resnet18_mini.h5'