input_shape :  [96, 96, 3]
encodings_len: 1024
mode : 'triplet'
distance_type : 'l1'
backbone : 'mobilenetv2'
backbone_weights : 'imagenet'
optimizer : 'radam'
learning_rate : 0.0001
project_name : 'road_signs/'
freeze_backbone : True

#paths
dataset_path : '/home/rauf/datasets/road_signs/road_signs_separated/'
tensorboard_log_path : 'tf_log/'
weights_save_path : 'weights/'
plots_path : 'plots/'
encodings_path : 'encodings/'
model_save_name : 'best_model_mobilenetv2.h5'