input_shape :  [48, 48, 3]
encodings_len: 4096
mode : 'triplet'
distance_type : 'l1'
backbone : 'simple2'
backbone_weights : 'imagenet'
optimizer : 'adam'
learning_rate : 0.0001
project_name : 'road_signs/'
freeze_backbone : True

#paths
dataset_path : '/home/rauf/plates_competition/dataset/road_signs/road_signs_separated/'
tensorboard_log_path : 'tf_log/'
weights_save_path : 'weights/'
plots_path : 'plots/'
encodings_path : 'encodings/'